In [20]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)

In [5]:
fire_all = pd.read_csv('./fire_all.csv', encoding = 'cp949')
fire_all.head()

C:\Users\caand\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (8,172,173,174,175,176,177,178,179) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,dt_of_fr,fr_yn,bldng_us,bldng_archtctr,bldng_cnt,bldng_ar,ttl_ar,lnd_ar,dt_of_athrztn,ttl_grnd_flr,...,no_tbc_zn_dstnc,bldng_cnt_in_50m,trgt_crtr,fr_fghtng_fclt_spcl_css_5_yn,fr_fghtng_fclt_spcl_css_6_yn,us_yn,dngrs_thng_yn,slf_fr_brgd_yn,blk_dngrs_thng_mnfctr_yn,cltrl_hrtg_yn
0,2017-10-20 05:54,Y,단독주택,블록구조,3,69.42,69.42,0.0,1977.0,1.0,...,88,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2018-09-30 08:26,N,NaN,NaN,3,46.29,46.29,0.0,NaN,1.0,...,7727,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2016-10-30 14:57,Y,공동주택,철근콘크리트구조,1,583.80,2516.76,1446.0,20001104.0,5.0,...,72,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2016-06-14 05:23,N,단독주택,일반목구조,2,48.92,48.92,0.0,1936.0,1.0,...,508,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2018-04-22 05:38,N,NaN,NaN,2,0.00,0.00,0.0,NaN,NaN,...,707,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
fire_feature = fire_all.iloc[:, [1,4,5,6,7,9,10,12,14,16,158,159,160,161,162,164,165,166,167,168,169,170,171]]

In [24]:
fire_feature

,fr_yn,bldng_cnt,bldng_ar,ttl_ar,lnd_ar,ttl_grnd_flr,ttl_dwn_flr,tmprtr,wnd_spd,hmdt,hm_cnt,fr_sttn_dstnc,bldng_ar_prc,fr_wthr_fclt_dstnc,fr_mn_cnt,cctv_dstnc,fr_wthr_fclt_in_100m,cctv_in_100m,tbc_rtl_str_dstnc,sft_emrgnc_bll_dstnc,ahsm_dstnc,no_tbc_zn_dstnc,bldng_cnt_in_50m
0,Y,3,69.42,69.42,0.00,1.0,0.0,10.7,0.9,96.0,17360.0,4547,NaN,133,137.0,112,0,0,1891,29231,11322,88,0
1,N,3,46.29,46.29,0.00,1.0,0.0,19.5,0.5,74.0,1791.0,6388,122581.0,489,85.0,818,0,0,4533,20480,3369,7727,0
2,Y,1,583.80,2516.76,1446.00,5.0,0.0,15.5,2.0,21.0,17285.0,3340,618105.0,143,137.0,165,0,0,277,31197,12451,72,14
3,N,2,48.92,48.92,0.00,1.0,0.0,20.6,0.4,91.0,7327.0,179,719542.0,1585,176.0,131,0,0,438,4270,407,508,11
4,N,2,0.00,0.00,0.00,NaN,NaN,12.7,0.6,89.0,17278.0,4822,NaN,603,137.0,686,0,0,1702,29778,12487,707,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66092,N,1,0.00,0.00,0.00,NaN,NaN,15.5,1.4,49.0,10068.0,3789,1288416.0,137,201.0,214,0,0,157,283,11358,256,0
66093,N,1,186.00,340.74,945.00,2.0,0.0,13.9,1.9,85.0,42257.0,2958,2216621.0,170,201.0,494,0,0,948,1180,21459,845,0
66094,Y,1,115.50,290.40,583.86,3.0,0.0,26.3,2.3,91.0,50835.0,2514,NaN,49,178.0,626,1,0,362,2535,2851,746,0
66095,N,1,139.05,378.84,234.10,3.0,0.0,-4.6,2.9,35.0,78252.0,1001,894800.0,115,201.0,70,0,1,115,209,16620,152,1
66096,Y,1,509.32,2669.72,1008.40,7.0,0.0,7.6,3.1,68.0,44178.0,600,1323248.0,133,201.0,68,0,1,201,107,19517,84,14

In [25]:
fire_feature.describe()

,bldng_cnt,bldng_ar,ttl_ar,lnd_ar,ttl_grnd_flr,ttl_dwn_flr,tmprtr,wnd_spd,hmdt,hm_cnt,fr_sttn_dstnc,bldng_ar_prc,fr_wthr_fclt_dstnc,fr_mn_cnt,cctv_dstnc,fr_wthr_fclt_in_100m,cctv_in_100m,tbc_rtl_str_dstnc,sft_emrgnc_bll_dstnc,ahsm_dstnc,no_tbc_zn_dstnc,bldng_cnt_in_50m
count,66097.000000,66097.000000,6.609700e+04,6.609700e+04,55092.000000,54167.000000,66083.000000,66060.000000,66072.000000,65395.000000,66097.000000,4.111600e+04,66097.000000,66055.000000,66097.000000,66097.000000,66097.000000,66097.000000,66097.000000,66097.000000,66097.000000,66097.000000
mean,3.326505,709.930469,3.234041e+03,2.708495e+04,3.587272,0.141378,14.125766,1.600772,65.416425,12916.961190,5375.582129,6.842093e+05,1735.017338,155.291348,709.723694,0.259240,0.407764,3020.091169,28356.010076,9559.645551,1111.025871,3.808191
std,6.919706,9412.103821,8.273613e+04,2.043907e+06,18.599150,1.013108,9.738308,1.334144,23.495065,16169.106876,4786.231654,5.294236e+05,2550.972216,36.964773,1277.600729,0.611271,1.133075,3245.027560,24630.329336,11114.215153,1606.611279,8.218508
min,1.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,-14.100000,0.000000,0.000000,778.000000,3.000000,1.753700e+04,0.000000,85.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000
25%,1.000000,49.590000,5.421000e+01,0.000000e+00,1.000000,0.000000,6.300000,0.600000,48.000000,3170.000000,1565.000000,2.974952e+05,103.000000,118.000000,97.000000,0.000000,0.000000,459.000000,8321.000000,939.000000,126.000000,0.000000
50%,2.000000,93.140000,1.014900e+02,1.861000e+02,1.000000,0.000000,14.800000,1.300000,68.000000,6036.000000,3866.000000,5.975640e+05,475.000000,164.000000,263.000000,0.000000,0.000000,1874.000000,23015.000000,4345.000000,422.000000,0.000000
75%,4.000000,170.860000,2.614000e+02,4.840000e+02,2.000000,0.000000,22.000000,2.300000,86.000000,14667.000000,7990.000000,9.158742e+05,2119.000000,178.000000,817.000000,0.000000,0.000000,4610.000000,41688.000000,15881.000000,1447.000000,3.000000
max,705.000000,572897.955000,1.235184e+07,2.038984e+08,594.000000,60.000000,38.100000,15.300000,100.000000,115081.000000,38044.000000,1.568930e+07,17716.000000,210.000000,12278.000000,10.000000,24.000000,23228.000000,103571.000000,56485.000000,16164.000000,84.000000

In [28]:
fire_feature = fire_feature.dropna(axis = 0)
fire_feature.describe()

,bldng_cnt,bldng_ar,ttl_ar,lnd_ar,ttl_grnd_flr,ttl_dwn_flr,tmprtr,wnd_spd,hmdt,hm_cnt,fr_sttn_dstnc,bldng_ar_prc,fr_wthr_fclt_dstnc,fr_mn_cnt,cctv_dstnc,fr_wthr_fclt_in_100m,cctv_in_100m,tbc_rtl_str_dstnc,sft_emrgnc_bll_dstnc,ahsm_dstnc,no_tbc_zn_dstnc,bldng_cnt_in_50m
count,37035.00000,37035.000000,3.703500e+04,3.703500e+04,37035.000000,37035.000000,37035.000000,37035.000000,37035.000000,37035.000000,37035.000000,3.703500e+04,37035.000000,37035.000000,37035.000000,37035.000000,37035.000000,37035.000000,37035.000000,37035.000000,37035.000000,37035.000000
mean,3.04061,417.520751,4.199096e+03,2.838194e+03,3.989766,0.136790,14.165670,1.594127,65.478828,13834.905333,5198.841474,6.854819e+05,1807.302930,156.368408,655.431376,0.286135,0.482382,2877.994087,28117.621844,9279.387687,1047.996706,4.206156
std,3.71482,5117.667807,1.063935e+05,1.408510e+05,22.025275,1.058746,9.676657,1.316034,23.381281,16930.711443,4770.327534,5.272497e+05,2631.566857,36.985588,1235.110745,0.634570,1.225056,3235.022440,24593.049217,10943.929044,1613.122702,8.653259
min,1.00000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,-14.100000,0.000000,0.000000,807.000000,20.000000,1.777500e+04,0.000000,85.000000,0.000000,0.000000,0.000000,0.000000,16.000000,0.000000,0.000000,0.000000
25%,1.00000,61.660000,6.666000e+01,0.000000e+00,1.000000,0.000000,6.400000,0.600000,48.000000,3370.000000,1412.000000,3.000000e+05,94.000000,118.000000,86.000000,0.000000,0.000000,388.000000,8416.500000,720.000000,113.000000,0.000000
50%,2.00000,91.910000,9.961000e+01,1.980000e+02,1.000000,0.000000,14.900000,1.300000,68.000000,6926.000000,3533.000000,5.992230e+05,441.000000,164.000000,199.000000,0.000000,0.000000,1596.000000,22791.000000,3791.000000,331.000000,0.000000
75%,4.00000,132.725000,1.941150e+02,3.900000e+02,2.000000,0.000000,22.000000,2.300000,86.000000,17003.000000,7900.500000,9.156625e+05,2278.000000,194.000000,753.000000,0.000000,0.000000,4451.000000,40973.500000,16206.000000,1307.000000,4.000000
max,117.00000,339687.880000,1.235184e+07,2.274090e+07,594.000000,60.000000,37.800000,13.900000,100.000000,115081.000000,35243.000000,1.568930e+07,14663.000000,210.000000,12278.000000,10.000000,24.000000,20186.000000,103424.000000,55626.000000,12005.000000,84.000000

In [35]:
fire_feature = fire_feature.reset_index(drop = True)
fire_feature

,fr_yn,bldng_cnt,bldng_ar,ttl_ar,lnd_ar,ttl_grnd_flr,ttl_dwn_flr,tmprtr,wnd_spd,hmdt,hm_cnt,fr_sttn_dstnc,bldng_ar_prc,fr_wthr_fclt_dstnc,fr_mn_cnt,cctv_dstnc,fr_wthr_fclt_in_100m,cctv_in_100m,tbc_rtl_str_dstnc,sft_emrgnc_bll_dstnc,ahsm_dstnc,no_tbc_zn_dstnc,bldng_cnt_in_50m
0,N,3,46.29,46.29,0.0,1.0,0.0,19.5,0.5,74.0,1791.0,6388,122581.0,489,85.0,818,0,0,4533,20480,3369,7727,0
1,Y,1,583.80,2516.76,1446.0,5.0,0.0,15.5,2.0,21.0,17285.0,3340,618105.0,143,137.0,165,0,0,277,31197,12451,72,14
2,N,2,48.92,48.92,0.0,1.0,0.0,20.6,0.4,91.0,7327.0,179,719542.0,1585,176.0,131,0,0,438,4270,407,508,11
3,Y,1,96.66,149.04,486.0,2.0,0.0,27.8,4.5,11.0,17278.0,4278,899087.0,294,137.0,210,0,0,1425,29709,11690,206,0
4,N,6,92.00,92.04,0.0,1.0,0.0,5.8,0.5,78.0,17302.0,2008,233594.0,310,137.0,519,0,0,1951,33829,13237,695,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37030,N,1,96.48,96.48,310.0,1.0,0.0,25.4,1.2,93.0,8375.0,359,614635.0,151,178.0,103,0,0,3169,5585,10050,148,19
37031,N,1,117.72,340.20,197.8,3.0,0.0,23.4,0.5,98.0,8566.0,1278,774250.0,87,201.0,36,0,1,491,480,17660,421,17
37032,N,1,186.00,340.74,945.0,2.0,0.0,13.9,1.9,85.0,42257.0,2958,2216621.0,170,201.0,494,0,0,948,1180,21459,845,0
37033,N,1,139.05,378.84,234.1,3.0,0.0,-4.6,2.9,35.0,78252.0,1001,894800.0,115,201.0,70,0,1,115,209,16620,152,1
37034,Y,1,509.32,2669.72,1008.4,7.0,0.0,7.6,3.1,68.0,44178.0,600,1323248.0,133,201.0,68,0,1,201,107,19517,84,14

In [37]:
for i in range(len(fire_feature)):
    if fire_feature['bldng_ar'][i] == 0:
        fire_feature['bldng_ar'][i] = None
    if fire_feature['ttl_ar'][i] == 0:
        fire_feature['ttl_ar'][i] = None
    if fire_feature['lnd_ar'][i] == 0:
        fire_feature['lnd_ar'][i] = None
    if fire_feature['ttl_grnd_flr'][i] == 0:
        fire_feature['ttl_grnd_flr'][i] = None
    if fire_feature['wnd_spd'][i] == 0:
        fire_feature['wnd_spd'][i] = None
    if fire_feature['hmdt'][i] == 0:
        fire_feature['hmdt'][i] = None

<ipython-input-37-96f775bb006d>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fire_feature['lnd_ar'][i] = None
<ipython-input-37-96f775bb006d>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fire_feature['wnd_spd'][i] = None
<ipython-input-37-96f775bb006d>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fire_feature['hmdt'][i] = None
<ipython-input-37-96f775bb006d>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fire_feature['bldng_ar'][i] = None
<ipython-input-37-96f775bb006d>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fire_feature['ttl_grnd_flr'][i] = None
<ipython-input-37-96f775bb006d>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fire_feature['ttl_ar'][i] = None

In [38]:
fire_feature = fire_feature.dropna(axis = 0)
fire_feature = fire_feature.reset_index(drop = True)
fire_feature.describe()

,bldng_cnt,bldng_ar,ttl_ar,lnd_ar,ttl_grnd_flr,ttl_dwn_flr,tmprtr,wnd_spd,hmdt,hm_cnt,fr_sttn_dstnc,bldng_ar_prc,fr_wthr_fclt_dstnc,fr_mn_cnt,cctv_dstnc,fr_wthr_fclt_in_100m,cctv_in_100m,tbc_rtl_str_dstnc,sft_emrgnc_bll_dstnc,ahsm_dstnc,no_tbc_zn_dstnc,bldng_cnt_in_50m
count,22322.000000,22322.000000,22322.000000,2.232200e+04,22322.000000,22322.000000,22322.000000,22322.000000,22322.000000,22322.000000,22322.000000,2.232200e+04,22322.000000,22322.000000,22322.000000,22322.000000,22322.000000,22322.000000,22322.000000,22322.000000,22322.000000,22322.000000
mean,2.554341,245.057264,1283.395998,4.567998e+03,2.697339,0.098244,14.388563,1.704018,64.461952,15283.599901,5253.465639,7.136623e+05,1718.548652,157.324971,625.002598,0.296613,0.491354,2840.948840,26908.843338,10802.010841,916.343562,3.964340
std,2.996456,2081.371779,16464.519379,1.809093e+05,11.606057,0.563576,9.639941,1.301697,23.062852,18572.712738,4953.605503,5.016987e+05,2601.277077,38.053201,1181.726743,0.633896,1.239857,3301.089218,25370.571778,11219.922567,1423.542794,8.172422
min,1.000000,4.750000,4.750000,1.562000e+00,1.000000,0.000000,-14.100000,0.100000,6.000000,814.000000,27.000000,1.784100e+04,0.000000,85.000000,0.000000,0.000000,0.000000,0.000000,22.000000,0.000000,0.000000,0.000000
25%,1.000000,72.800000,78.127500,2.104000e+02,1.000000,0.000000,6.600000,0.700000,47.000000,3473.250000,1438.000000,3.526805e+05,89.000000,118.000000,83.000000,0.000000,0.000000,370.000000,4036.500000,1021.000000,107.000000,0.000000
50%,2.000000,99.785000,116.780000,3.180000e+02,1.000000,0.000000,15.100000,1.400000,66.000000,7276.500000,3442.000000,6.538955e+05,350.000000,174.000000,191.000000,0.000000,0.000000,1484.000000,18934.500000,7042.000000,293.000000,0.000000
75%,3.000000,140.795000,233.822500,5.370000e+02,2.000000,0.000000,22.200000,2.400000,84.000000,19513.000000,7871.750000,9.394485e+05,2097.750000,194.000000,718.750000,0.000000,0.000000,4317.500000,43723.750000,18621.250000,1145.000000,4.000000
max,117.000000,159966.100000,727058.154000,2.274090e+07,413.000000,20.000000,37.800000,13.900000,100.000000,115081.000000,35243.000000,1.125876e+07,14663.000000,210.000000,12278.000000,10.000000,24.000000,20186.000000,103424.000000,55626.000000,11993.000000,72.000000

In [39]:
fire_feature

,fr_yn,bldng_cnt,bldng_ar,ttl_ar,lnd_ar,ttl_grnd_flr,ttl_dwn_flr,tmprtr,wnd_spd,hmdt,hm_cnt,fr_sttn_dstnc,bldng_ar_prc,fr_wthr_fclt_dstnc,fr_mn_cnt,cctv_dstnc,fr_wthr_fclt_in_100m,cctv_in_100m,tbc_rtl_str_dstnc,sft_emrgnc_bll_dstnc,ahsm_dstnc,no_tbc_zn_dstnc,bldng_cnt_in_50m
0,Y,1,583.80,2516.76,1446.0,5.0,0.0,15.5,2.0,21.0,17285.0,3340,618105.0,143,137.0,165,0,0,277,31197,12451,72,14
1,Y,1,96.66,149.04,486.0,2.0,0.0,27.8,4.5,11.0,17278.0,4278,899087.0,294,137.0,210,0,0,1425,29709,11690,206,0
2,Y,2,98.96,98.96,310.0,1.0,0.0,0.1,0.6,66.0,17199.0,2583,263117.0,66,137.0,46,1,2,135,31585,12101,18,7
3,N,1,44.22,129.55,82.0,3.0,0.0,10.3,0.9,24.0,17282.0,2215,652729.0,79,137.0,113,1,0,474,31441,11505,52,12
4,Y,4,81.36,81.36,640.0,1.0,0.0,6.2,0.1,93.0,17170.0,3536,1129748.0,107,137.0,95,0,0,739,30400,11694,58,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22317,N,1,96.48,96.48,310.0,1.0,0.0,25.4,1.2,93.0,8375.0,359,614635.0,151,178.0,103,0,0,3169,5585,10050,148,19
22318,N,1,117.72,340.20,197.8,3.0,0.0,23.4,0.5,98.0,8566.0,1278,774250.0,87,201.0,36,0,1,491,480,17660,421,17
22319,N,1,186.00,340.74,945.0,2.0,0.0,13.9,1.9,85.0,42257.0,2958,2216621.0,170,201.0,494,0,0,948,1180,21459,845,0
22320,N,1,139.05,378.84,234.1,3.0,0.0,-4.6,2.9,35.0,78252.0,1001,894800.0,115,201.0,70,0,1,115,209,16620,152,1
22321,Y,1,509.32,2669.72,1008.4,7.0,0.0,7.6,3.1,68.0,44178.0,600,1323248.0,133,201.0,68,0,1,201,107,19517,84,14